=== GSA/code-gov-api/schemas/general-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "version": {
            "type": "string",
            "enum": [
                "1.0.1",
                "2.0.0"
            ]
        },
        "measurementType": {
            "type": "object",
            "description": "An object containing description of the open source measurement method. ",
            "properties": {
                "method": {
                    "type": "string",
                    "enum": [
                        "cost",
                        "system",
                        "projects",
                        "modules",
                        "linesOfCode",
                        "other"
                    ],
                    "description": "An enumerated list of methods for measuring the open source requirement. "
                },
                "ifOther": {
                    "type": "string",
                    "description": "A one- or two- sentence description of the measurement type used, if 'other' is selected as the value of 'method' field."
                }
            }
        },
        "agency": {
            "type": "string",
            "description": "The agency acronym for Clinger Cohen Act (CCA) agencies can be found through the CFO Act list, as CCA references the CFO Act. For example \"GSA\" or \"DOD\". Please use uppercase letters."
        },
        "releases": {
            "type": "array",
            "items": {
                "type":"object"
            }
        }
    },
    "additionalProperties": false,
    "required":[
        "version",
        "measurementType",
        "releases"
    ]
}

=== GSA/code-gov-api/data/fallback/TREASURY.json
{
  "agency": "TREASURY",
  "version": "2.0.0",
  "measurementType": {
    "method": "modules"
  },
  "releases": [
    {
      "name": "data-act-broker-web-app",
      "description": "The DATA Act broker website is the front-end to the DATA Act broker backend.",
      "permissions": {
        "licenses": null,
        "usageType": "governmentWideReuse",
        "exemptionText": null
      },
      "tags": [
        "spending",
        "government",
        "transparency"
      ],
      "contact": {
        "email": "Renata.Maziarz@fiscal.treasury.gov"
      },
      "repositoryURL": "https://github.com/fedspendingtransparency/data-act-broker-web-app",
      "laborHours": 0
    },
    {
      "name": "data-act-broker-backend",
      "description": "The DATA Act broker backend is a collection of services that power the DATA Act's central data submission platform.",
      "permissions": {
        "licenses": null,
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "spending",
        "government",
        "transparency",
        "broker"
      ],
      "contact": {
        "email": "Renata.Maziarz@fiscal.treasury.gov"
      },
      "repositoryURL": "https://github.com/fedspendingtransparency/data-act-broker-backend",
      "laborHours": 0
    },
    {
      "name": "federal spending transparency",
      "description": "This collaboration space is designed to make federal spending data more accessible, searchable, reliable and meet the transparency requirements of the DATA Act.",
      "permissions": {
        "licenses": null,
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "spending",
        "government",
        "transparency",
        "Federal"
      ],
      "contact": {
        "email": "Renata.Maziarz@fiscal.treasury.gov"
      },
      "repositoryURL": "https://github.com/fedspendingtransparency/fedspendingtransparency.github.io",
      "laborHours": 0
    },
    {
      "name": "IDES-Data-Preparation-Java",
      "description": "The IDES Data Preparation Java project repository demonstrates a sample working application developed using Java.",
      "permissions": {
        "licenses": null,
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "IRS",
        "FATCA",
        "IDES"
      ],
      "contact": {
        "email": "lbi.fatca.ides@irs.gov"
      },
      "repositoryURL": "http://irsgov.github.io/IDES-Data-Preparation-Java",
      "laborHours": 0
    },
    {
      "name": "IDES-Data-Preparation-Dot-Net",
      "description": "The IDES Data Preparation .NET project repository demonstrates a sample working application developed using .NET",
      "permissions": {
        "licenses": null,
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "IRS",
        "FATCA",
        "IDES"
      ],
      "contact": {
        "email": "lbi.fatca.ides@irs.gov"
      },
      "repositoryURL": "http://irsgov.github.io/IDES-Data-Preparation-Dot-Net",
      "laborHours": 0
    }
  ]
}

=== GSA/code-gov-api/data/fallback/FEC.json
{
  "agency": "FEC",
  "measurementType": {
    "ifOther": "TBD",
    "method": "other"
  },
  "releases": [
    {
      "organization": "Federal Election Commission",
      "contact": {
        "URL": "https://github.com/fecgov/fec/issues",
        "email": "opensource@fec.gov"
      },
      "date": {
        "created": "2018-08-03T12:50:00+00:00",
        "lastModified": "2018-08-03T12:49:57+00:00",
        "metadataLastUpdated": "2018-08-03T12:49:57+00:00"
      },
      "description": "A general discussion forum for FEC.gov. This is the best place to submit general feedback.",
      "downloadURL": "https://api.github.com/repos/fecgov/FEC/downloads",
      "homepageURL": "https://github.com/fecgov/FEC",
      "laborHours": 1092.0,
      "languages": [],
      "name": "FEC",
      "permissions": {
        "usageType": "openSource",
        "licenses": [
          {
            "URL": "https://github.com/fecgov/FEC/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ]
      },
      "repositoryURL": "https://github.com/fecgov/FEC",
      "status": "Production",
      "tags": [
        "FEC",
        "github",
        "feedback",
        "discussion"
      ],
      "vcs": "git"
    },
    {
      "organization": "Federal Election Commission",
      "contact": {
        "URL": "https://github.com/fecgov/fec/issues",
        "email": "opensource@fec.gov"
      },
      "date": {
        "created": "2018-08-07T14:55:33+00:00",
        "lastModified": "2018-08-06T20:48:06+00:00",
        "metadataLastUpdated": "2018-08-03T12:49:57+00:00"
      },
      "description": "The first RESTful API for the Federal Election Commission. We're aiming to make campaign finance more accessible for journalists, academics, developers, and other transparency seekers.",
      "downloadURL": "https://api.github.com/repos/fecgov/openFEC/downloads",
      "homepageURL": "https://api.open.fec.gov/developers/",
      "laborHours": 204966.6666666667,
      "languages": [
        "Python",
        "PLpgSQL",
        "JavaScript",
        "HTML",
        "SQLPL",
        "Shell",
        "CSS"
      ],
      "name": "openFEC",
      "permissions": {
        "usageType": "openSource",
        "licenses": [
          {
            "URL": "https://github.com/fecgov/openFEC/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ]
      },
      "repositoryURL": "https://github.com/fecgov/openFEC",
      "status": "Production",
      "tags": [
        "FEC",
        "github",
        "API",
        "campaign finance"
      ],
      "vcs": "git"
    },
    {
      "organization": "Federal Election Commission",
      "contact": {
        "URL": "https://github.com/fecgov/fec/issues",
        "email": "opensource@fec.gov"
      },
      "date": {
        "created": "2018-08-08T04:21:05+00:00",
        "lastModified": "2018-08-06T16:12:26+00:00",
        "metadataLastUpdated": "2018-08-03T12:49:57+00:00"
      },
      "description": "The content management system (CMS) for the new Federal Election Commission website.",
      "downloadURL": "https://api.github.com/repos/fecgov/fec-cms/downloads",
      "homepageURL": "https://www.fec.gov",
      "laborHours": 46696.0,
      "languages": [
        "HTML",
        "JavaScript",
        "Python",
        "CSS",
        "Shell"
      ],
      "name": "fec-cms",
      "permissions": {
        "usageType": "openSource",
        "licenses": [
          {
            "URL": "https://github.com/fecgov/fec-cms/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ]
      },
      "repositoryURL": "https://github.com/fecgov/fec-cms",
      "relatedCode": [
        {
          "name": "U.S. Web Design System",
          "URL": "https://github.com/uswds/uswds"
        }
      ],
      "status": "Production",
      "tags": [
        "FEC",
        "github",
        "agency website",
        "content"
      ],
      "vcs": "git"
    },
    {
      "organization": "Federal Election Commission",
      "contact": {
        "URL": "https://github.com/fecgov/fec/issues",
        "email": "opensource@fec.gov"
      },
      "date": {
        "created": "2018-07-12T15:14:41+00:00",
        "lastModified": "2018-07-12T15:14:38+00:00",
        "metadataLastUpdated": "2018-08-03T12:49:57+00:00"
      },
      "description": "Reverse proxy app to combine multiple applications.",
      "downloadURL": "https://api.github.com/repos/fecgov/fec-proxy/downloads",
      "homepageURL": "https://github.com/fecgov/fec-proxy",
      "laborHours": 52.0,
      "languages": [],
      "name": "fec-proxy",
      "permissions": {
        "usageType": "openSource",
        "licenses": [
          {
            "URL": "https://github.com/fecgov/fec-proxy/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ]
      },
      "repositoryURL": "https://github.com/fecgov/fec-proxy",
      "status": "Production",
      "tags": [
        "FEC",
        "github",
        "proxy"
      ],
      "vcs": "git"
    },
    {
      "organization": "Federal Election Commission",
      "contact": {
        "URL": "https://github.com/fecgov/fec/issues",
        "email": "opensource@fec.gov"
      },
      "date": {
        "created": "2018-07-17T17:12:41+00:00",
        "lastModified": "2018-07-17T14:46:12+00:00",
        "metadataLastUpdated": "2018-08-03T12:49:57+00:00"
      },
      "description": "The Federal Election Commission's web-based application that makes regulations easier to find, read and understand.",
      "downloadURL": "https://api.github.com/repos/fecgov/fec-eregs/downloads",
      "homepageURL": "https://www.fec.gov/regulations",
      "laborHours": 8406.666666666668,
      "languages": [
        "CSS",
        "HTML",
        "Python",
        "JavaScript"
      ],
      "name": "fec-eregs",
      "permissions": {
        "usageType": "openSource",
        "licenses": [
          {
            "URL": "https://github.com/fecgov/fec-eregs/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ]
      },
      "repositoryURL": "https://github.com/fecgov/fec-eregs",
      "relatedCode": [
        {
          "name": "regulations-core",
          "URL": "https://github.com/eregs/regulations-core"
        },
        {
          "name": "regulations-site",
          "URL": "https://github.com/eregs/regulations-site"
        },
        {
          "name": "regulations-parser",
          "URL": "https://github.com/eregs/regulations-parser"
        }
      ],
      "status": "Production",
      "tags": [
        "FEC",
        "github",
        "regulations",
        "search",
        "eRegs",
        "CFR"
      ],
      "vcs": "git"
    },
    {
      "organization": "Federal Election Commission",
      "contact": {
        "URL": "https://github.com/fecgov/fec/issues",
        "email": "opensource@fec.gov"
      },
      "date": {
        "created": "2018-07-02T22:12:06+00:00",
        "lastModified": "2018-06-13T23:12:32+00:00",
        "metadataLastUpdated": "2018-08-03T12:49:57+00:00"
      },
      "description": "Pattern Library for the new FEC.gov",
      "downloadURL": "https://api.github.com/repos/fecgov/fec-pattern-library/downloads",
      "homepageURL": "https://fec-pattern-library.app.cloud.gov/",
      "laborHours": 11110.666666666666,
      "languages": [
        "HTML",
        "JavaScript",
        "CSS",
        "Shell"
      ],
      "name": "fec-pattern-library",
      "permissions": {
        "usageType": "openSource",
        "licenses": [
          {
            "URL": "https://github.com/fecgov/fec-pattern-library/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ]
      },
      "repositoryURL": "https://github.com/fecgov/fec-pattern-library",
      "relatedCode": [
        {
          "name": "U.S. Web Design System",
          "URL": "https://github.com/uswds/uswds"
        }
      ],
      "status": "Production",
      "tags": [
        "FEC",
        "github",
        "styles",
        "design patterns"
      ],
      "vcs": "git"
    },
    {
      "organization": "Federal Election Commission",
      "contact": {
        "URL": "https://github.com/fecgov/fec/issues",
        "email": "opensource@fec.gov"
      },
      "date": {
        "created": "2018-05-29T23:58:34+00:00",
        "lastModified": "2018-05-29T23:58:31+00:00",
        "metadataLastUpdated": "2018-08-03T12:49:57+00:00"
      },
      "description": "Terraform configuration and CircleCI for managing custom FEC infrastructure in AWS.",
      "downloadURL": "https://api.github.com/repos/fecgov/fec-infrastructure/downloads",
      "homepageURL": "https://github.com/fecgov/fec-infrastructure",
      "laborHours": 17.333333333333336,
      "languages": [
        "HCL"
      ],
      "name": "fec-infrastructure",
      "permissions": {
        "usageType": "openSource",
        "licenses": [
          {
            "URL": "https://github.com/fecgov/fec-infrastructure/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ]
      },
      "repositoryURL": "https://github.com/fecgov/fec-infrastructure",
      "status": "Production",
      "tags": [
        "FEC",
        "github",
        "ferraform",
        "configuration",
        "AWS"
      ],
      "vcs": "git"
    }
  ],
  "version": "2.0.0"
}

=== GSA/code-gov-api/data/fallback/USAID.json
{
  "version": "2.0.0",
  "agency": "USAID",
  "measurementType": {},
  "releases": [
    {
      "name": "Gmail Imap Pop Disable",
      "description": "Allows a gmail enterprise to authorize only a limited number of users the ability to connect to Gmail using POP or IMAP. Any other users who configure that option which are not in the authorized list will have the connection disabled.",
      "tags": [
        "Gmail",
        "Imap"
      ],
      "contact": {
        "email": "mdicko@usaid.gov",
        "name": "Malcolm Dicko",
        "phone": "703-666-1215"
      },
      "repositoryURL": "https://github.com/USAID-MCIO/USAIDGmailImapPopDisable-",
      "permissions": {
        "licenses": [
          {
            "URL": "null",
            "name": "null"
          }
        ],
        "exemptionText": "null"
      },
      "laborHours": 300,
      "date": {
        "created": "",
        "lastModified": "",
        "metadataLastUpdated": ""
      },
      "vcs": "",
      "disclaimerText": "",
      "disclaimerURL": "",
      "relatedCode": [
        {
          "isGovernmentRepo": true
        }
      ],
      "reusedCode": [
        {
          "name": "",
          "URL": ""
        }
      ]
    },
    {
      "name": "Save Gmail",
      "manifest_version": 2,
      "description": "USAID Gmail extension to save messages to local disk",
      "tags": [
        "SAVE",
        "GMAIL"
      ],
      "contact": {
        "email": "mdicko@usaid.gov",
        "name": "Malcolm Dicko",
        "phone": "703-666-1215"
      },
      "repositoryURL": "https://github.com/USAID-MCIO/USAIDGmailSaveMessageExtension-",
      "permissions": {
        "licenses": [
          {
            "URL": "null",
            "name": "null"
          }
        ],
        "usageType": "governmentWideReuse",
        "exemptionText": null
      },
      "laborHours": 300,
      "date": {
        "created": "",
        "lastModified": "",
        "metadataLastUpdated": ""
      },
      "vcs": "",
      "disclaimerText": "",
      "disclaimerURL": "",
      "relatedCode": [
        {
          "isGovernmentRepo": true
        }
      ],
      "reusedCode": [
        {
          "name": "",
          "URL": ""
        }
      ]
    }
  ]
}

=== GSA/code-gov-api/data/fetched/VA.json
{
  "agency": "VA",
  "version": "2.0.0",
  "measurementType": {
    "method": "modules"
  },
  "releases": [
    {
      "name": "Caseflow Certification",
      "repositoryURL": "https://github.com/department-of-veterans-affairs/caseflow",
      "description": "Caseflow is a web application tracking and processing appealed claims at theVA Board of Veterans' Appeals.",
      "permissions": {
        "licenses": [
          {
            "URL": "https://github.com/department-of-veterans-affairs/caseflow/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ],
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "VA",
        "Veteran",
        "Appeal",
        "Workflow",
        "Benefits"
      ],
      "contact": {
        "email": "ossoft@va.gov"
      },
      "organization": "OIT EPMO",
      "languages": [
        "Ruby"
      ],
      "laborHours": 0,
      "status": "Development",
      "vcs": "git"
    },
    {
      "name": "Vets.gov",
      "repositoryURL": "https://github.com/department-of-veterans-affairs/vets-website",
      "description": "Vets.gov is the consolidation of several critical Veteran-facing applications into a single web-based launchpad.",
      "permissions": {
        "licenses": [
          {
            "URL": "https://github.com/department-of-veterans-affairs/vets-website/blob/master/LICENSE",
            "name": "CC0"
          }
        ],
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "VA",
        "Veteran",
        "Benefits"
      ],
      "contact": {
        "email": "ossoft@va.gov"
      },
      "organization": "OIT EPMO",
      "languages": [
        "JavaScript"
      ],
      "laborHours": 0
    },
    {
      "name": "Vets.gov APIs",
      "repositoryURL": "https://github.com/department-of-veterans-affairs/vets-api",
      "description": "This project provides common APIs for applications that live on vets.gov.",
      "permissions": {
        "licenses": [
          {
            "URL": "https://github.com/department-of-veterans-affairs/vets-api/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ],
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "VA",
        "Veteran",
        "Benefits",
        "api"
      ],
      "contact": {
        "email": "ossoft@va.gov"
      },
      "organization": "OIT EPMO",
      "languages": [
        "Ruby"
      ],
      "laborHours": 0
    },
    {
      "name": "Veterans Employment Center",
      "repositoryURL": "https://github.com/department-of-veterans-affairs/veterans-employment-center",
      "description": "Veterans Employment Center creates a website of links that assist a Veteran in a job search.",
      "permissions": {
        "licenses": null,
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "VA",
        "Veteran",
        "job"
      ],
      "contact": {
        "email": "ossoft@va.gov"
      },
      "organization": "OIT EPMO",
      "languages": [
        "Ruby"
      ],
      "laborHours": 0
    },
    {
      "name": "GIBCT Data Service",
      "repositoryURL": "https://github.com/department-of-veterans-affairs/gibct-data-service",
      "description": "GIDS compiles data from federal CSV-formatted sources into institution profiles to provide school metrics to the GI Bill Comparison Tool.",
      "permissions": {
        "licenses": [
          {
            "URL": "https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/LICENSE.md",
            "name": "CC0"
          }
        ],
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "GIBCT",
        "school",
        "Veteran",
        "Benefits"
      ],
      "contact": {
        "email": "ossoft@va.gov"
      },
      "organization": "OIT EPMO",
      "languages": [
        "Ruby"
      ],
      "laborHours": 0
    },
    {
      "name": "GI Bill Comparison Tool",
      "repositoryURL": "https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool",
      "description": "The GI Bill Comparison Tool allows a Veteran to compare education benefits among potential schools.",
      "permissions": {
        "licenses": null,
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "GIBCT",
        "school",
        "Veteran",
        "Benefits"
      ],
      "contact": {
        "email": "ossoft@va.gov"
      },
      "organization": "OIT EPMO",
      "languages": [
        "Ruby"
      ],
      "laborHours": 0
    },
    {
      "name": "Choice Act Locator",
      "repositoryURL": "https://github.com/department-of-veterans-affairs/ChoiceActLocator",
      "description": "This web mapping application provides veterans the ability to search and find Non-VA Care providers through the Choice Act.",
      "permissions": {
        "licenses": null,
        "usageType": "openSource",
        "exemptionText": null
      },
      "tags": [
        "Choice Act",
        "Veteran",
        "Benefits"
      ],
      "contact": {
        "email": "ossoft@va.gov"
      },
      "organization": "OIT EPMO",
      "languages": [
        "JavaScript"
      ],
      "laborHours": 0
    }
  ]
}
